version: '3'

services:
  sparc-app-2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sparc-app-2:latest
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    command: yarn dev
