[project]
name = "promptme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "openai>=1.98.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.0",
]
